# Generated by Django 5.2.3 on 2025-06-17 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_equipmentstata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='equipment_type',
            field=models.ManyToManyField(related_name='equipment_types', to='equipment.equipmenttype', verbose_name='Тип снаряжения'),
        ),
    ]
