# Generated by Django 5.2.3 on 2025-06-17 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_alter_equipment_equipment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='recipe_items',
            field=models.ManyToManyField(help_text='Элементы из которых сделан предмет', related_name='recipe_items', to='equipment.equipment', verbose_name='Рецент'),
        ),
    ]
