# Generated by Django 5.2.3 on 2025-06-17 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0004_equipment_recipe_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='recipe_items',
            field=models.ManyToManyField(help_text='Элементы из которых сделан предмет', related_name='recipe_items', to='equipment.equipment', verbose_name='Рецепт'),
        ),
    ]
