# Generated by Django 5.2.3 on 2025-06-17 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0007_equipmentpassive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='short_description',
            field=models.TextField(blank=True, null=True, verbose_name='Краткое описание'),
        ),
    ]
