# Generated by Django 5.2.3 on 2025-06-17 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0008_alter_equipment_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='recipe_items',
            field=models.ManyToManyField(blank=True, help_text='Элементы из которых сделан предмет', null=True, to='equipment.equipment', verbose_name='Рецепт'),
        ),
    ]
