# Generated by Django 5.2.3 on 2025-06-16 08:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ed191a78-f7cf-41dc-9fd3-7d27bc43b1f5'), editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
