# Generated by Django 5.2.3 on 2025-06-21 06:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSpecialty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название специализации')),
                ('description', models.TextField(blank=True, verbose_name='Описание специализации')),
            ],
            options={
                'verbose_name': 'Специализация героя',
                'verbose_name_plural': 'Специализации героев',
                'abstract': False,
            },
        ),
    ]
