# Generated by Django 5.2.3 on 2025-06-16 08:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emblem',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('ed191a78-f7cf-41dc-9fd3-7d27bc43b1f5'), editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='emblems/icons/', verbose_name='Иконка')),
                ('emblem_type', models.CharField(choices=[('BASE', 'Обычная эмблема'), ('TANK', 'Танк'), ('ASSASSIN', 'Убийца'), ('MAGE', 'Маг'), ('FIGHTER', 'Боец'), ('SUPPORT', 'Поддержка'), ('MARKSMAN', 'Стрелок')], max_length=50, verbose_name='Тип эмблемы')),
            ],
            options={
                'verbose_name': 'Эмблема',
                'verbose_name_plural': 'Эмблемы',
            },
        ),
    ]
